# Define platform
platform :ios, '12.0'

# Use dynamic frameworks
use_frameworks!
use_modular_headers!

# Load Flutter CocoaPods helper script
flutter_root = File.expand_path('..', File.dirname(__FILE__))
load File.join(flutter_root, 'ios', 'flutter', 'tools', 'podhelper.rb')

target 'Runner' do
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
